name: Deploy example

on:
  push:
    branches: [ "main", "gh-pages" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ github.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
