name: Deploy example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22'

    - name: Install and Build
      run: |
        mkdir -p dist
        cd wasm
        ./build.sh
        mv main.wasm ../dist
        cd ../dist
        cp ../example/public/index.html .
        cp ../example/public/index.js .
        cp ../example/public/test.dxf .
        curl https://raw.githubusercontent.com/golang/go/refs/heads/master/lib/wasm/wasm_exec.js > wasm_exec.js

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        ssh-key: ${{ secrets.DEPLOY_KEY }}
